### ISSUE TITLE
Uniqueness metric implementation may have issue

### ISSUE THREAD

**Issue by chaitjo** [atomicarchitects/molmetrics#2]
https://github.com/atomicarchitects/molmetrics/blob/main/molmetrics/rdkit/uniqueness.py#L16

The method get_all_unique_molecules seems to return all the molecules instead of only the unique ones.

It will always return uniqueness as 100% because of this. You can try it yourself by taking any RDKit molecule, creating a couple copies of it into a list, and pass that list to the method.

I believe the method should do something like this:
```python
def get_all_unique_molecules(molecules: Sequence[Chem.Mol]) -> Sequence[Chem.Mol]:
    """Returns all unique molecules."""
    smiles2mol = {}
    for mol in molecules:
        smiles = Chem.MolToSmiles(mol)
        if smiles not in smiles2mol:
            smiles2mol[smiles] = mol

    return smiles2mol.values()
```

**Comment by ameya98** [comment]
Ah F good catch! As you can see this is very much a work-in-progress :) Planning to also add some tests soon to avoid this in the future.

**Comment by ameya98** [comment]
Should be fixed! Thanks again!
